# Generated by Django 3.2.6 on 2021-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio', models.CharField(max_length=30)),
                ('cuota_mensual', models.FloatField()),
                ('pagoTotal', models.IntegerField()),
                ('tasaInteresM', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tasa', models.FloatField()),
                ('montoDisponible', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'socios',
            },
        ),
    ]
